/**
 * MMM-GooglePhotos Configuration Example - V3 (Google Drive Migration)
 *
 * This example shows the new configuration options for the Drive API version.
 */

{
  module: "MMM-GooglePhotos",
  position: "fullscreen_below",
  config: {
    // ===========================================
    // NEW in V3: Google Drive Folder Configuration
    // ===========================================
    // Replace 'albums' with 'driveFolders'
    driveFolders: [
      {
        id: "1a2b3c4d5e6f7g8h9i0j",  // Folder ID from Google Drive URL
        depth: -1                     // -1 = infinite recursion
                                      //  0 = only this folder (no subfolders)
                                      //  N = N levels deep
      },
      {
        id: "2b3c4d5e6f7g8h9i0j1k",  // Another folder
        depth: 0                      // Only this folder, no subfolders
      },
      {
        id: null,                     // null = Drive root folder
        depth: 1                      // Only 1 level deep from root
      }
    ],

    // ===========================================
    // NEW in V3: Authentication File Paths
    // ===========================================
    // Path to your Google Drive OAuth credentials
    keyFilePath: "./google_drive_auth.json",  // Default

    // Path to your OAuth token (generated by generate_drive_token.js)
    tokenPath: "./token_drive.json",          // Default

    // ===========================================
    // NEW in V3: Cache Settings
    // ===========================================
    // Maximum cache size in MB (default: 200MB = ~5-6 hours offline)
    maxCacheSizeMB: 200,

    // How often to scan Drive for new photos (default: 6 hours)
    scanInterval: 1000 * 60 * 60 * 6,  // 6 hours in milliseconds

    // ===========================================
    // NEW in V3: Offline Mode & Authentication Retry
    // ===========================================
    // Maximum authentication retry attempts (default: Infinity)
    // Set to a number to limit retries, or Infinity to retry forever
    maxAuthRetries: Infinity,

    // Maximum backoff time between authentication retries (default: 120000ms = 2 minutes)
    // Retry backoff starts at 5s and doubles each attempt up to this maximum
    maxAuthBackoffMs: 120000,  // 2 minutes

    // ===========================================
    // NEW in V3: Photo Sort Mode
    // ===========================================
    // How to order photos for display
    // Options:
    //   'sequential' - Show photos in order by ID (no skipping, deterministic)
    //   'random'     - Random order each cycle
    //   'newest'     - Show newest photos first (by creation/upload date)
    //   'oldest'     - Show oldest photos first (by creation/upload date)
    sortMode: 'sequential',           // Default: 'sequential'

    // Note: All modes prioritize unviewed photos first, then cycle through viewed photos

    // ===========================================
    // NEW in V3: BLOB Storage & Image Processing
    // ===========================================
    // Enable BLOB storage (stores images in database instead of loose files)
    // Requires 'sharp' library: npm install sharp
    useBlobStorage: true,             // Default: true (if sharp is installed)
    jpegQuality: 85,                  // JPEG quality (1-100, default: 85)

    // ===========================================
    // UNCHANGED: Display Settings (same as V2)
    // ===========================================
    // How often to change photos (default: 60 seconds, minimum: 10 seconds)
    updateInterval: 1000 * 60,  // 60 seconds

    // Display resolution (used for image resizing & quality)
    showWidth: 1080,
    showHeight: 1920,

    // Time format for photo metadata
    timeFormat: "YYYY/MM/DD HH:mm",

    // Auto-position info overlay
    autoInfoPosition: false,

    // ===========================================
    // REMOVED in V3: These options no longer work
    // ===========================================
    // ❌ albums: []           - Use driveFolders instead
    // ❌ sort: "new"/"old"    - Not yet implemented in V3
    // ❌ uploadAlbum: null    - Not implemented in V3
    // ❌ condition: {...}     - Not yet implemented in V3 (filter by date/size)

    // ===========================================
    // DEBUG Mode
    // ===========================================
    debug: false  // Enable verbose logging
  }
}

/**
 * How to get Google Drive Folder ID:
 *
 * 1. Open Google Drive in your browser
 * 2. Navigate to the folder you want to use
 * 3. Look at the URL in your browser:
 *    https://drive.google.com/drive/folders/1a2b3c4d5e6f7g8h9i0j
 *                                           ^^^^^^^^^^^^^^^^^^^^
 *                                           This is the folder ID
 * 4. Copy the ID and paste it into your config
 *
 * For Drive root: Use null as the folder ID
 */

/**
 * Minimal Configuration Example:
 */
{
  module: "MMM-GooglePhotos",
  position: "fullscreen_below",
  config: {
    driveFolders: [
      { id: "YOUR_FOLDER_ID_HERE", depth: -1 }
    ]
  }
}

/**
 * Migration from V2 to V3:
 *
 * OLD (V2 - Google Photos):
 * {
 *   albums: ["Family Photos", "Vacation 2024"]
 * }
 *
 * NEW (V3 - Google Drive):
 * {
 *   driveFolders: [
 *     { id: "1a2b3c4d5e6f7g8h9i0j", depth: -1 },  // Family Photos folder
 *     { id: "2b3c4d5e6f7g8h9i0j1k", depth: -1 }   // Vacation 2024 folder
 *   ]
 * }
 */
